name: rustls

permissions:
  contents: read

on:
  push:
    branches: ['main', 'ci/*']
  pull_request:
  merge_group:
  #schedule:
    #- cron: '0 18 * * *'
  workflow_dispatch:

jobs:
  build:
    name: Build+test
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        # test a bunch of toolchains on ubuntu
        rust:
          - stable
          #- beta
          #- nightly
        #os: [ubuntu-latest]
        # but only stable on macos/windows (slower platforms)
        include:
          - os: macos-13-xlarge
            rust: stable
          #- os: windows-latest
            #rust: stable
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      #- name: Install ${{ matrix.rust }} toolchain
        #uses: dtolnay/rust-toolchain@master
        #with:
          #toolchain: ${{ matrix.rust }}

      #- name: Install NASM for aws-lc-rs on Windows
        #if: runner.os == 'Windows'
        #uses: ilammy/setup-nasm@v1

      - name: run macOS integration test
        if: matrix.os == 'macos-13-xlarge'
        run: bash integration-tests/macos.sh
