name: myrustls
on:
  workflow_dispatch:  

jobs:
  test-with-cert:
    #runs-on: macos-14
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-13, macos-14 ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add PEM certificate to trust store 
        run: |
          sudo security authorizationdb write com.apple.trust-settings.admin allow
          sudo security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain integration-tests/one-existing-ca.pem
          echo "Certificate added to trust store."
          
      - name: Check the certificate's presence and trust status
        run: |
          security find-certificate -a -c "GlobalSign" /Library/Keychains/System.keychain || echo "Not found"
      
      - name: Manually try the removing trust certificate.
        run: |
          CERT_HASH=$(openssl x509 -in integration-tests/one-existing-ca.pem -noout -fingerprint -sha1 | cut -d= -f2 | tr -d ':')
          sudo security delete-certificate -Z "$CERT_HASH" /Library/Keychains/System.keychain
      - name: Check the certificate's presence and trust status
        run: |
          security find-certificate -a -c "GlobalSign" /Library/Keychains/System.keychain || echo "Not found"
