name: rustls

permissions:
  contents: read

on:
  push:
    branches: ['main', 'ci/*']
  pull_request:
  merge_group:
  #schedule:
    #- cron: '0 18 * * *'
  workflow_dispatch:

jobs:
  build:
    name: Build+test
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        # test a bunch of toolchains on ubuntu
        rust:
          - stable
          #- beta
          #- nightly
        #os: [ubuntu-latest]
        # but only stable on macos/windows (slower platforms)
        include:
          - os: macos-14
            rust: stable
          #- os: windows-latest
            #rust: stable
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install ${{ matrix.rust }} toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}

      - name: Install NASM for aws-lc-rs on Windows
        if: runner.os == 'Windows'
        uses: ilammy/setup-nasm@v1

      - name: cargo build (debug; default features)
        run: cargo build --locked

      - name: cargo test (debug; default features)
        run: cargo test --locked
        env:
          RUST_BACKTRACE: 1

      - name: cargo test (debug; all features)
        run: cargo test --locked --all-features
        env:
          RUST_BACKTRACE: 1

      - name: cargo build (debug; no default features)
        run: cargo build --locked --no-default-features

      - name: cargo test (debug; no default features; no run)
        run: cargo test --locked --no-default-features --no-run

      - name: cargo test (release; no run)
        run: cargo test --locked --release --no-run

      - name: run macOS integration test
        if: matrix.os == 'macos-14'
        run: sudo bash integration-tests/macos.sh
